### PR TITLE
Inpsyde PR Challenge

### PR DESCRIPTION
**Pull request by JackJohansson**
This PR was by demand of Inpsyde as a challenge.

Thanks for contributing to Adminimize &mdash; you rock!

Please note:
- These comments won't show up when you submit the pull request.
- Please make sure your changes respect the WordPress Coding Standards:
  - https://make.wordpress.org/core/handbook/best-practices/coding-standards/
- In case you introduced a new action or filter hook, please also include appropriate inline documentation:
  - https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters
- In case you added or changed assets, please make sure you did this in the resources/ folder.
- If you Grunt installed, please run `grunt pre-commit` before committing your changes.
-->

This pull request fixes issue #.

#### What's Included in this Pull Request
* The changes are noted in the comments.

### CODE REVIEW

**Comment by bueltge** [comment]
Hi @JackJohansson 
Really thanks for your request! 
However our intention was to get a pull request to the refactor branch, there store the new version, writing really new, from scratch. 
But, it is not an problem, all your topics are right and necessary also for this current version, there I had the source ;) That's was the point that we rewrite the plugin.

Have you also tested the plugin, actitve in usage? It is important for me, especially there you have removed global vars, there have in this bad code no dependence to his file.

**Comment by JackJohansson** [comment]
Hi @bueltge 

Sorry about that, next time I will ask more details before I commit to something.

And yes, I copied the Repo files to my plugins, and edited it on an active local installation. There were a few bugs ( even before I commit any change ) while saving the settings, such as front-end admin bar setting ( not being saved ), but changes that i made didn't create any issue, to the extent that I know.

By the way, if it is necessary, I can create another PR to the refactor for the challenge, however I don't know if it's okay to take a few more days to do this. Should I discuss this in the job application?

**Comment by bueltge** [comment]
No problem for now. The hint about this request form your mail should have include the hint for the branch 'refactor'.

A request is not necessary for you, because you have create the WP Nonce topic, that I valid before. If you will, please send me request, it is really great and helpful for the plugin and the users, there will use a better version. I hope we can realize a new refactored version of the plugin, that's makes easier for me to tests and maintain the solution.

**Comment by JackJohansson** [comment]
Sure. I'll be happy to help. So if there's nothing else to do here, this PR can be closed.

**Comment by bueltge** [comment]
I will merge them, after a validation from my side, is also helpful and will not trash your effort.

**Pull request merged**
