### PR TITLE
Added filter to adminimizeoptions and 2 actions to add rows to the mi…

### PR DESCRIPTION
**Pull request by g-kanoufi**
#### What's Included in this Pull Request
* adminimizeoptions filter
* 2 actions to add rows to the minimenu

### CODE REVIEW

**Comment by bueltge** [comment]
Why you filter the options? Reduce you this for custom installs?

**Comment by g-kanoufi** [comment]
Hi Frank,

We are using the filter on adminimizeoptions to be able to add our custom needs for it, as i couldn't find another way to add custom options, this is how i did it.

Let me know if there is another solution.

Thank you

--
Guillaume Kanoufi

**Comment by bueltge** [comment]
Currently you have only the possibility to add options via the custom options field, manual. So the hook is a good idea.
I will merge them in view days, currently to much work and family topics.

**Comment by g-kanoufi** [comment]
No problem that's cool, happy holidays :)


--
Guillaume Kanoufi

**Comment by bueltge** [comment]
also c1d61d3a42a4464ee7d231e4c6c46d182ac85690

**Pull request merged**
