### PR TITLE
Followup PR: Tabs and Code Coverage exclusion

### PR DESCRIPTION
**Pull request by dugajean**
@bueltge Like we discussed in the other PR, the tabs needed to fit the WordPress design. In order to do that, I implemented a simple tab solution in jQuery and removed the jQueryUI dependency. jQueryUI tabs required the use of `ul/ol` and list items - otherwise it wouldn't have worked. Since the requirement was simple enough, the jQuery solution should be good to go.

For the Code Coverage issue and the failing tests, adding the exclusion in `phpunit.xml.dist` as discussed fixes the problem.

### CODE REVIEW

**Comment by bueltge** [comment]
Hi @dugajean Big thanks again to you for your PR, great work. I will check that manual in my dev environment for UI topics with the simpler jQuery solution. However is great idea to keep simpler.

**Comment by dugajean** [comment]
@bueltge Thanks a lot for merging in the changes! Yeah I thought so too about the tabs; In this case, simple works just fine. 😄

**Comment by dugajean** [comment]
Hi @bueltge 

I'll check these out and see what's going on. Thanks for letting me know.

**Comment by bueltge** [comment]
You have right, it works. I have active a privacy badger :( So for now is deactivated and it works, `tabs()' is not longer unknown.

**Comment by dugajean** [comment]
Ah alright... I was wondering what the issue could be. Thanks for letting me know.

I have created #114 and it fixes the rest of the problems.

**Pull request merged**
